Specify UTM zone instead of lon_0
pyproj.exceptions.CRSError: Invalid projection:
+proj=utm +ellps=WGS84 +lon_0=37.688200664169585 +type=crs:
(Internal Proj Error: proj_create: Invalid zone number)

It seems to be necessary to specify the UTM zone when transforming
coordinates via the op_transform function when option +proj=utm is used.
See: https://savannah.gnu.org/bugs/?61086